global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'grpc-local'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'grpc-prod'
    static_configs:
      - targets: [ 'my_app:9090' ]
